
package japicmp.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jApiJavaObjectSerializationChangeStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="jApiJavaObjectSerializationChangeStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NOT_SERIALIZABLE"/>
 *     &lt;enumeration value="SERIALIZABLE_COMPATIBLE"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_SERIALVERSIONUID_MODIFIED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_SERIALVERSIONUID_REMOVED_AND_NOT_MACHTES_NEW_DEFAULT"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_SERIALVERSIONUID_ADDED_AND_NOT_MATCHES_OLD_DEFAULT"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_CLASS_TYPE_MODIFIED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_CHANGED_FROM_SERIALIZABLE_TO_EXTERNALIZABLE"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_CHANGED_FROM_EXTERNALIZABLE_TO_SERIALIZABLE"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_SERIALIZABLE_REMOVED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_EXTERNALIZABLE_REMOVED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_FIELD_REMOVED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_FIELD_CHANGED_FROM_NONSTATIC_TO_STATIC"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_FIELD_CHANGED_FROM_NONTRANSIENT_TO_TRANSIENT"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_FIELD_TYPE_MODIFIED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_BUT_SUID_EQUAL"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_CLASS_REMOVED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_DEFAULT_SERIALVERSIONUID_CHANGED"/>
 *     &lt;enumeration value="SERIALIZABLE_INCOMPATIBLE_SUPERCLASS_MODIFIED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "jApiJavaObjectSerializationChangeStatus")
@XmlEnum
public enum JApiJavaObjectSerializationChangeStatus {

    NOT_SERIALIZABLE,
    SERIALIZABLE_COMPATIBLE,
    SERIALIZABLE_INCOMPATIBLE_SERIALVERSIONUID_MODIFIED,
    SERIALIZABLE_INCOMPATIBLE_SERIALVERSIONUID_REMOVED_AND_NOT_MACHTES_NEW_DEFAULT,
    SERIALIZABLE_INCOMPATIBLE_SERIALVERSIONUID_ADDED_AND_NOT_MATCHES_OLD_DEFAULT,
    SERIALIZABLE_INCOMPATIBLE_CLASS_TYPE_MODIFIED,
    SERIALIZABLE_INCOMPATIBLE_CHANGED_FROM_SERIALIZABLE_TO_EXTERNALIZABLE,
    SERIALIZABLE_INCOMPATIBLE_CHANGED_FROM_EXTERNALIZABLE_TO_SERIALIZABLE,
    SERIALIZABLE_INCOMPATIBLE_SERIALIZABLE_REMOVED,
    SERIALIZABLE_INCOMPATIBLE_EXTERNALIZABLE_REMOVED,
    SERIALIZABLE_INCOMPATIBLE_FIELD_REMOVED,
    SERIALIZABLE_INCOMPATIBLE_FIELD_CHANGED_FROM_NONSTATIC_TO_STATIC,
    SERIALIZABLE_INCOMPATIBLE_FIELD_CHANGED_FROM_NONTRANSIENT_TO_TRANSIENT,
    SERIALIZABLE_INCOMPATIBLE_FIELD_TYPE_MODIFIED,
    SERIALIZABLE_INCOMPATIBLE_BUT_SUID_EQUAL,
    SERIALIZABLE_INCOMPATIBLE_CLASS_REMOVED,
    SERIALIZABLE_INCOMPATIBLE_DEFAULT_SERIALVERSIONUID_CHANGED,
    SERIALIZABLE_INCOMPATIBLE_SUPERCLASS_MODIFIED;

    public String value() {
        return name();
    }

    public static JApiJavaObjectSerializationChangeStatus fromValue(String v) {
        return valueOf(v);
    }

}
